### ISSUE TITLE
HI

### ISSUE THREAD

**Issue by s312580** [logue/MabiPack#9]
It has recently updated the package file to "data_00001.it" file. Is there a way to extract the data again?
它最近更新了package的檔案改為"data_00001.it"檔，請問有方法可以再拆資料出來嗎?
最近、パッケージファイルを「data_00001.it」ファイルに更新しました。データを再度抽出する方法はありますか？
최근에 패키지 파일을 "it" 파일로 업데이트했는데 다시 데이터를 추출할 수 있는 방법이 없을까요?

**Comment by logue** [comment]
I checked the latest client's package directory but couldn't find a file of that format.

If you have a question about the inside of the pack file, I cannot answer it.
As you can see in the explanation, this tool is made only for the purpose of decompressing and creating pack files, and the internal files are not completely cured.

**Comment by shaggyze** [comment]
> I checked the latest client's package directory but couldn't find a file of that format.
> 
> If you have a question about the inside of the pack file, I cannot answer it. As you can see in the explanation, this tool is made only for the purpose of decompressing and creating pack files, and the internal files are not completely cured.

I believe he's referring to China's server, and yea .IT requires a whole nother unpacking method.

**Comment by logue** [comment]
Are’nt you looking at another place? This is the state with the latest patch applied earlier. The current client package directory should have this file structure.
I don't know the other specifications.
![image](https://user-images.githubusercontent.com/480173/146325343-e75c2ff2-af63-4e6f-abe2-b5460e6052d1.png)

**Comment by aum555** [comment]
I play on TW server and this the new package folder structure:
![image](https://user-images.githubusercontent.com/66254762/150118016-e1dea98d-7d56-41f6-be99-b5a64224447c.png)

The update file seems be chopped into a few smaller files.

The header of the files are different now, maybe it is encrypted?
From a normal .pack file:
![image](https://user-images.githubusercontent.com/66254762/150117832-c9d2647b-82dc-4a80-bc0e-2ca54edcf334.png)

From the new .it file:
![image](https://user-images.githubusercontent.com/66254762/150118223-35b5af8c-8802-48ad-8759-e11a0cb095d4.png)

**Comment by logue** [comment]
Oh really.

It's difficult because I can't confirm it because I can't create a local account from Japan. Perhaps Japanese clients will follow suit, but I've been away from Mabinogi for quite some time, so I can't afford to catch up on the latest information.

So I declare the **end of the project** (contains [MabinogiResource](https://github.com/logue/MabinogiResource) with the current time.

Thank you for using it so far.
